import {
  createWorker,
  QueueContainer,
  WorkerContainer,
} from "@csi-foxbyte/fastify-toab";
import { getBlobStorageService } from "../blobStorage.service.js";
import defaultConnection from "../../connection.js";
import { Job } from "bullmq";

const deleteBlobWorker = createWorker()
  .queue("{deleteBlob-queue}")
  .job<Job<{ containerName: string; blobName: string }, void>>()
  .options({
    removeOnComplete: { count: 0 },
    removeOnFail: { count: 100 },
  })
  .connection(defaultConnection)
  .processor(async (job, { services }) => {
    const blobStorageService = await getBlobStorageService(services);

    await blobStorageService.delete(job.data.containerName, job.data.blobName);

    return;
  });

/*
AUTOGENERATED!
*/

export { deleteBlobWorker };
export type DeleteBlobWorker = (typeof deleteBlobWorker)["worker"];
export type DeleteBlobWorkerQueue = (typeof deleteBlobWorker)["queue"];
export type DeleteBlobWorkerJob = (typeof deleteBlobWorker)["job"];

export function getDeleteBlobWorker(deps: WorkerContainer) {
  return deps.get<DeleteBlobWorker>(deleteBlobWorker.queueName);
}
export function getDeleteBlobWorkerQueue(deps: QueueContainer) {
  return deps.get<DeleteBlobWorkerQueue>(deleteBlobWorker.queueName);
}
