import { createService } from "@csi-foxbyte/fastify-toab";
import {
  getPrismaService,
  getProjectService,
} from "../@internals/index.js";
import dayjs from "dayjs";

const userService = createService("user", async ({ services }) => {
  const prismaService = await getPrismaService(services);
  const projectService = await getProjectService(services);

  async function remove(id: string) {
    const projects = await prismaService.project.findMany({
      where: { ownerId: id },
      select: { id: true },
    });

    for (const project of projects) {
      await projectService.deleteProject(project.id);
    }

    await prismaService.user.delete({ where: { id } });
  }

  return {
    remove,
    async removeInactiveUsers() {
      const users = await prismaService.user.findMany({
        where: {
          sessions: {
            every: {
              updatedAt: {
                lt: dayjs().add(30, "day").toISOString(),
              },
            },
          },
        },
      });

      for (const user of users) {
        await remove(user.id);
      }
    },
    async info(id: string) {
      const user = await prismaService.user.findFirstOrThrow({
        where: { id },
        select: {
          name: true,
          email: true,
        },
      });

      return {
        ...user,
        name: user.name ?? "-",
      };
    },
  };
});

/*
AUTOGENERATED!
*/

export default userService;
