import {
  createService,
  InferService,
  ServiceContainer,
} from "@csi-foxbyte/fastify-toab";
import { prisma } from "../prisma/index.js";
import { enhance, Enhanced } from "@zenstackhq/runtime";
import { getAuthService } from "../auth/auth.service.js";

const dbService = createService("db", async ({ services }) => {
  return {
    rawClient: prisma,
    /**
     * Needs to be called within a request context!
     * @returns
     */
    getEnhancedClient() {
      return new Promise<Enhanced<typeof prisma>>(async (resolve, reject) => {
        const authService = await getAuthService(services);

        try {
          const session = await authService.getSession();

          if (!session) throw new Error("Unauthenticated!");

          resolve(enhance(prisma, session));
        } catch (e) {
          return reject(e);
        }
      });
    },
  };
});

/*
AUTOGENERATED!
*/

export { dbService };
export type DbService = InferService<typeof dbService>;
export function getDbService(deps: ServiceContainer) {
  return deps.get<DbService>(dbService.name);
}
