import { createController } from "@csi-foxbyte/fastify-toab";
import { authMiddleware } from "../auth/auth.middleware.js";

const projectController = createController()
    .use(authMiddleware)
    .rootPath("/project")

/*
AUTOGENERATED!
*/

export { projectController };
