import {
  createService,
  InferService,
  ServiceContainer,
} from "@csi-foxbyte/fastify-toab";
import { createCache } from "cache-manager";

const cacheService = createService("cache", async () => {
  const cache = createCache();

  return cache;
});

/*
AUTOGENERATED!
*/

export { cacheService };
export type CacheService = InferService<typeof cacheService>;
export function getCacheService(deps: ServiceContainer) {
  return deps.get<CacheService>(cacheService.name);
}
